// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqOuBXGl_IHSDtIgF_ccClbc3P-5kjr70',
    appId: '1:1099080661698:android:1062ed6ef4b0cdb55f595b',
    messagingSenderId: '1099080661698',
    projectId: 'vpn-sebek',
    storageBucket: 'vpn-sebek.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qKj-890HHSgStA6xCQr2l7HSYKBzuOE',
    appId: '1:1099080661698:ios:1f1d654253b528e65f595b',
    messagingSenderId: '1099080661698',
    projectId: 'vpn-sebek',
    storageBucket: 'vpn-sebek.appspot.com',
    androidClientId: '1099080661698-0m07r63dgsb6ps9kkkn6tlc5trpgmlmi.apps.googleusercontent.com',
    iosClientId: '1099080661698-38qm2s2eurcm6hjffe4a131r8d5u798f.apps.googleusercontent.com',
    iosBundleId: 'com.vpnsebek.vpnSebek',
  );
}
